development:
  adapter: mysql2
  encoding: utf8
  database: kuppayam_development
  username: root
  password: 
  port: 3306
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: kuppayam_test
  username: root
  password: 
  port: 3306
  host: localhost
